//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZA
    {
        public int ID_POLIZA { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string AUTO_MARCA { get; set; }
        public string AUTO_MODELO { get; set; }
        public string AUTO_ANIO { get; set; }
        public string DANIOS { get; set; }
        public string SGM { get; set; }
        public string VIDA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_VIGENCIA { get; set; }
        public decimal COSTO { get; set; }
        public decimal PORC_COASEGURADO { get; set; }
        public decimal PORC_DEDUCIBLE { get; set; }
        public string COBERTURA { get; set; }
    }
}
